### PR TITLE
Update GNMStart.txt

### PR DESCRIPTION
**Pull request by MNevs**

### CODE REVIEW

**Comment by GodDragoner** [comment]
"@Info(ChastityIsOn) @Flag(ChastityTrainingActive) @NullResponse @Goto(Unlock)"  "@Info"?

**Comment by MNevs** [comment]
@info is only a comment it should mean from now on is the code only for chastityIsOn
And @Flag(ChastityTrainingActive) is only to be save. While ChastityTraining is active you never start a session with a chastity belt on. Or?

**Comment by GodDragoner** [comment]
You do. At some point it is: You should really try to wear it until next session. But I guess the flag is still never set then.

**Comment by MNevs** [comment]
I  checked it at the moment again and at the end the by the exam it set the flag

**Comment by MNevs** [comment]
i change it thank you

**Pull request merged**
